import './globals.css'
import '@rainbow-me/rainbowkit/styles.css';
// #############
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { headers } from 'next/headers'
import { type ReactNode } from 'react'
// #############


import { Providers } from './providers';

// #############
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Wagmi',
    description: 'Generated by create-wagmi',
}
// #############

function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}

export default RootLayout;
